// ДАНІ ПРОЄКТІВ
const projectsData = [
  { "id": "nier-replicant", "title": "NieR Replicant ver.1.22...", "cover": "assets/nier_replicant.webp", "logo": "assets/nier_replicant_logo.webp", "status": "in-progress", "progress": 8, "progress_text": 8, "progress_textures": 0, "progress_fonts": 100, "desc": "Інтерфейс і субтитри українською.", "desc_en": "UI and subtitles in Ukrainian.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "videos": ["https://www.youtube.com/watch?v=qF6WHQ-qjvw"] },
  { "id": "dispatch", "title": "Dispatch", "cover": "assets/Dispatch.webp", "logo": "assets/Dispatch_logo.webp", "status": "in-progress", "progress": 50, "progress_mode": "episodes", "progress_ep1": 100, "progress_ep2": 100, "progress_ep3": 100, "progress_ep4": 100, "progress_ep5": 58, "progress_ep6": 0, "progress_ep7": 0, "progress_ep8": 0, "desc": "Текстова українська локалізація чотирьох епізодів.", "desc_en": "Text Ukrainian localization of four episodes.", "cta": { "type": "enabled", "label": "Завантажити", "label_en": "Download", "url": "https://drive.google.com/file/d/1PxV-wsFB8PS5a2RaCHhxfS7OaAGfRt7R/view?usp=sharing", "primary": true }, "videos": ["https://www.youtube.com/watch?v=JnsQQNCTCPs"] },
  { "id": "lad", "title": "Yakuza: Like a Dragon", "cover": "assets/LaD.webp", "logo": "assets/LaD_logo.webp", "status": "fundraising", "raised": 11220, "goal": 35000, "progress": 20, "progress_text": 20, "progress_textures": 35, "progress_fonts": 90, "desc": "Збір на українську локалізацію: інтерфейс, субтитри.", "desc_en": "Fundraising for Ukrainian localization: UI, subtitles.", "cta": { "type": "enable", "label": "Спонсорувати", "label_en": "Sponsor", "url": "https://donatello.to/LittleBitUA", "primary": true }, "steam": "https://store.steampowered.com/app/1235140/Yakuza_Like_a_Dragon/", "videos": ["https://www.youtube.com/watch?v=dhObkWG-goU"] },
  { "id": "mgs2", "title": "MGS 2: Sons of Liberty", "cover": "assets/MGS2.webp", "logo": "assets/MGS2_Logo.webp", "status": "fundraising", "raised": 13246, "goal": 25000, "progress": 15, "progress_text": 15, "progress_textures": 0, "progress_fonts": 100, "desc": "Збір на українську локалізацію: інтерфейс, субтитри.", "desc_en": "Fundraising for Ukrainian localization: UI, subtitles.", "cta": { "type": "enable", "label": "Спонсорувати", "label_en": "Sponsor", "url": "https://donatello.to/LittleBitUA", "primary": true }, "steam": "https://store.steampowered.com/app/2131660/", "videos": ["https://www.youtube.com/watch?v=14EBz2UG1vI"] },
  { "id": "uncharted-df", "title": "Uncharted: Drake's Fortune", "cover": "assets/Uncharted.webp", "logo": "assets/Uncharted_logo.webp", "status": "early-access", "progress": 82, "progress_text": 86, "progress_textures": 0, "progress_fonts": 100, "desc": "Повний текстовий переклад. Інтерфейс і субтитри.", "desc_en": "Full text translation. UI and subtitles.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "videos": ["https://www.youtube.com/watch?v=3O6n4R-69sc"] },
  { "id": "uncharted-2", "title": "Uncharted 2: Among Thieves", "cover": "assets/Uncharted2.webp", "logo": "assets/Uncharted2_Logo.webp", "status": "fundraising", "raised": 1110, "goal": 8000, "progress": 8, "progress_text": 8, "progress_textures": 0, "progress_fonts": 100, "desc": "Збір на українську локалізацію: інтерфейс, субтитри.", "desc_en": "Fundraising for Ukrainian localization: UI, subtitles.", "cta": { "type": "enable", "label": "Спонсорувати", "label_en": "Sponsor", "url": "https://donatello.to/LittleBitUA", "primary": true }, "videos": [] },
  { "id": "hotel-barcelona", "title": "HOTEL BARCELONA", "cover": "assets/barcelona.webp", "logo": "assets/barcelona_logo.webp", "status": "in-progress", "progress": 50, "progress_text": 50, "progress_textures": 0, "progress_fonts": 70, "desc": "Авторський проєкт SWERY та SUDA51. Локалізація у процесі.", "desc_en": "SWERY and SUDA51 project. Localization in progress.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/2286600/HOTEL_BARCELONA/", "videos": ["https://www.youtube.com/watch?v=VW4ZfUZ1wI4"] },
  { "id": "jojo-asbr", "title": "JoJo's Bizarre Adventure: ASBR", "cover": "assets/jojo_asbr.webp", "logo": "assets/jojo_asbr_logo.webp", "status": "in-progress", "progress": 4, "progress_text": 5, "progress_textures": 0, "progress_fonts": 100, "desc": "Повна текстова українська локалізація.", "desc_en": "Full text Ukrainian localization.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/1372110/", "videos": ["https://www.youtube.com/watch?v=MMTx8IkFBXg"] },
  { "id": "judgment", "title": "Judgment", "cover": "assets/judgment_takayuki.webp", "logo": "assets/judgment_logo.webp", "status": "early-access", "progress": 89, "progress_text": 89, "progress_textures": 50, "progress_fonts": 100, "desc": "Неонуарний детектив. Переклад підісторій та інтерфейсу.", "desc_en": "Neo-noir detective. Substories and UI translation.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://donatello.to/post/68de432ff7753d8d33210ca4/ukrayinizator-dlya-judgment-ranniy-dostup-donatello-2-02-10-2025", "primary": true }, "steam": "https://store.steampowered.com/app/2058180/Judgment/", "videos": ["https://www.youtube.com/watch?v=8cnFlWRILKY"] },
  { "id": "lost-judgment", "title": "Lost Judgment", "cover": "assets/lost_judgment.webp", "logo": "assets/lost_judgment_logo.webp", "status": "in-progress", "progress": 6, "progress_text": 6, "progress_textures": 0, "progress_fonts": 60, "desc": "Продовження історії Яґамі. Сюжет та інтерфейс.", "desc_en": "Yagami's story continues. Story and UI translation.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/2058180/Lost_Judgment/", "videos": ["https://www.youtube.com/watch?v=wx2OMw06t58"] },
  { "id": "ishin", "title": "Like a Dragon: Ishin!", "cover": "assets/Ishin.webp", "logo": "assets/Ishin_Logo.webp", "status": "in-progress", "progress": 15, "progress_text": 15, "progress_textures": 0, "progress_fonts": 60, "desc": "Історична пригода. Сюжет та субтитри.", "desc_en": "Historical adventure. Story and subtitles.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/1805480/Like_a_Dragon_ISHIN/", "videos": ["https://www.youtube.com/watch?v=eRTaJJn9ldI"] },
  { "id": "yk2", "title": "Yakuza Kiwami 2", "cover": "assets/yakuza_kiwami2.webp", "logo": "assets/yakuza_kiwami2_logo.webp", "status": "in-progress", "progress": 60, "progress_text": 90, "progress_textures": 30, "progress_fonts": 100, "desc": "Культовий ремейк. Переклад підісторій та інтерфейсу.", "desc_en": "Cult remake. Substories and UI translation.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/927380/Yakuza_Kiwami_2/", "videos": ["https://www.youtube.com/watch?v=wKe05u8sT_s"] },
  { "id": "y3", "title": "Yakuza 3 Remastered", "cover": "assets/yakuza_3_remastered.webp", "logo": "assets/yakuza3_logo.webp", "status": "in-progress", "progress": 14, "progress_text": 14, "progress_textures": 0, "progress_fonts": 100, "desc": "Той самий пляжний епізод. Переклад оригінальної гри та ремейку.", "desc_en": "The iconic beach episode. Translation of original and remake.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/1088710/Yakuza_3_Remastered/", "videos": ["https://www.youtube.com/watch?v=N25iZVyPLeI"] },
  { "id": "nmh1", "title": "No More Heroes", "cover": "assets/no_more_heroes_travis.webp", "logo": "assets/no_more_heroes_logo.webp", "status": "early-access", "progress": 86, "progress_text": 90, "progress_textures": 90, "progress_fonts": 100, "desc": "Пригода Тревіса Тачдауна. Сюжет, туторіали, інтерфейс.", "desc_en": "Travis Touchdown's adventure. Story, tutorials, UI.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/1420290/No_More_Heroes/", "videos": ["https://www.youtube.com/watch?v=tkDdmZFxWbE"] },
  { "id": "nmh2", "title": "No More Heroes 2", "cover": "assets/no_more_heroes_2.webp", "logo": "assets/no_more_heroes2_logo.webp", "status": "early-access", "progress": 100, "progress_text": 100, "progress_textures": 40, "progress_fonts": 100, "desc": "Ще більше стилю та боїв!", "desc_en": "Even more style and combat!", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://t.me/LittleBitUA/95", "primary": true }, "steam": "https://store.steampowered.com/app/1420300/", "videos": ["https://www.youtube.com/watch?v=8HGKIRc7MB8"] },
  { "id": "tsa", "title": "Travis Strikes Again", "cover": "assets/travis_strikes_again.webp", "logo": "assets/travis_strikes_again_logo.webp", "status": "in-progress", "progress": 23, "progress_text": 23, "progress_textures": 0, "progress_fonts": 100, "desc": "Експериментальний спін-оф.", "desc_en": "Experimental spin-off.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/1010100/", "videos": ["https://www.youtube.com/watch?v=YP8a4amktGE"] },
  { "id": "nmh3", "title": "No More Heroes 3", "cover": "assets/no_more_heroes_3.webp", "logo": "assets/no_more_heroes3_logo.webp", "status": "early-access", "progress": 100, "progress_text": 100, "progress_textures": 60, "progress_fonts": 100, "desc": "Надери дупу прибульцям! Сюжет та інтерфейс.", "desc_en": "Kick some alien butt! Story and UI.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://t.me/LittleBitUA/95", "primary": true }, "steam": "https://store.steampowered.com/app/1744330/No_More_Heroes_3/", "videos": ["https://www.youtube.com/watch?v=ZmbOIwUhC24"] },
  { "id": "dp1", "title": "Deadly Premonition", "cover": "assets/DP1.webp", "logo": "assets/DP1_Logo.webp", "status": "in-progress", "progress": 37, "progress_text": 37, "progress_textures": 0, "progress_fonts": 100, "desc": "Культовий містичний трилер. Сюжет та інтерфейс.", "desc_en": "Cult mystery thriller. Story and UI.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/247660/", "videos": ["https://www.youtube.com/watch?v=zIdPzW-H8gI"] },
  { "id": "dp2", "title": "Deadly Premonition 2", "cover": "assets/DP2.webp", "logo": "assets/DP2_Logo.webp", "status": "in-progress", "progress": 15, "progress_text": 15, "progress_textures": 0, "progress_fonts": 100, "desc": "Сиквел трилера з дивакуватим шармом.", "desc_en": "Sequel to the cult thriller.", "cta": { "type": "disabled", "label": "Завантажити", "label_en": "Download", "url": "#" }, "steam": "https://store.steampowered.com/app/1271100/", "videos": ["https://www.youtube.com/watch?v=66F3TanyZzI"] }
];

// ДАНІ ДОБРОЧИНЦІВ
const benefactorsList = [
    {name: "VADKO", type: "gold"}, {name: "Krov", type: "gold"},
    {name: "Хоук", type: "green"}, {name: "Hlamingo", type: "flamingo"},
    {name: "BreadHood"}, {name: "grafdralkuma"}, {name: "Мимокрокодил"},
    {name: "Volodymyr"}, {name: "anonymous"}, {name: "Дмитро"}, {name: "Македонський"},
    {name: "Рома"}, {name: "Jobitronik"}, {name: "AlviSeed"}, {name: "HorseBH"},
    {name: "Владислав"}, {name: "Nodertuk"}, {name: "Артур К"}, {name: "Валто"},
    {name: "Uatarasas"}, {name: "smutok"}, {name: "Костянтин"}, {name: "SPOQ"},
    {name: "Віталій"}, {name: "Fan"}, {name: "Сатаносексуалка"}, {name: "UnknownTheHero"},
    {name: "Нудьга"}, {name: "YarosTop1GG"}, {name: "Павло"}, {name: "Kazeiro Artist💗"},
    {name: "Jean Kartösciante"}, {name: "JoJo"}, {name: "Окунь"}, {name: "Мухобієчка"},
    {name: "beesexyial"}, {name: "Володимир"}, {name: "Бісик"}, {name: "Ігор Д."},
    {name: "Олексій Мороз"}, {name: "SpY_129"}, {name: "Billey"}, {name: "Іван Кіпрв"},
    {name: "KAREMBO"}, {name: "соня"}, {name: "rage"}, {name: "Бурʼян"}, {name: "LoydiN"},
    {name: "Андрійко"}, {name: "Смуток"}, {name: "Misha"}, {name: "Мемна Арта"},
    {name: "Микита"}, {name: "Мирослав Сеник"}, {name: "Andryxa"}, {name: "Богдан Городюк"},
    {name: "Дмитро С."}, {name: "Andrii Kravchenko"}, {name: "Вова ЇЖ"}, {name: "Dima Feyleg"},
    {name: "Дмитро"}, {name: "офіцерППО"}, {name: "Ігор"}, {name: "Артем"},
    {name: "Ton"}, {name: "Ярослав"}, {name: "BlackWolf94"}
];
